// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int times = Integer.parseInt(args[0]);
		int timesgreatest = 0;
		int timeslowest = 0;
		for (int i = 0; i < times; i++) {
			double j = Math.random();
			if (j <= 0.5) {
				timesgreatest += 1;
			} else {
				timeslowest += 1;
			}
		}
		System.out.println("> 0.5:  " + timeslowest + " times");
		System.out.println("<= 0.5  " + timesgreatest + " times");
		System.out.println("Ratio:  " + (double)(Math.min(timesgreatest,timeslowest) 
		/ (double)Math.max(timesgreatest,timeslowest)));
	}
}
